
#stage 1 Frontend build 
FROM node:20-alpine AS frontend_bulilder 

WORKDIR /app

COPY ./Frontend/package*.json /app

RUN npm install

COPY ./Frontend /app    

RUN npm run build

# stage 2  full backend build (image)

FROM node:20-alpine AS backend_builder

WORKDIR /app

COPY ./Backend/package*.json /app

RUN npm install

COPY ./Backend /app


COPY --from=frontend_bulilder /app/dist /app/public

CMD [ "node " , "server.js" ]


