    # FROM node:20-alpine
    # COPY package.json .
    # COPY package-lock.json .
    # RUN npm install
    # COPY .. . 

    # CMD ["npm run", "dev"]

# Base Image
FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

CMD ["node", "server.js"]